### ISSUE TITLE
Slow down ball

### ISSUE THREAD

**Issue by dashersw** [GallagherAiden/footballSimulationEngine#18]
The ball movement resolution sometimes work great, but most of the time it still teleports to a new location. I suspect it's because of the power applied to the ball — this might need further tuning. Given how small the players can move within an iteration, the ball should slow down significantly.

**Comment by GallagherAiden** [comment]
hmm, I've been creating relational movement based on power, so that as power decreases (over time and distance - e.g. because of resistance) the ball slows down. So a power and distance of 100 over 4 iterations would move:
Iteration 1: 40
Iteration 2: 30
Iteration 3: 20
Iteration 4: 10

Maybe, it would be more prudent to have a set minimum and maximum ball movement per iteration and power influences the number of iterations it takes for the ball to move that distance. This could also be aligned to future improvements for player speed.

Will fix before the next npm push, alongside existing refactoring tasks.

**Comment by dashersw** [comment]
@GallagherAiden maybe you need more iterations? What if the distance is less than 40? In a given iteration, a ball can maybe at most move 2-3x the max speed of a running player, but not more.

**Comment by GallagherAiden** [comment]
Ball is slowed down and only moves a maximum of 4 to 6 total spaces in the first iteration (since players can sprint at 2 spaces per move e.g. 2-3x). It then reduces as it moves further away. 

@dashersw, Could you take a look at the ball movement to see if it now fits better?

**Comment by GallagherAiden** [comment]
Please reopen if ball movement is still too fast

**Comment by dashersw** [comment]
Thank you @GallagherAiden , it's good, but I observed some other problems. Will write in detail later.

**Comment by GallagherAiden** [comment]
players are currently getting stuck in a single place as a result of the refactoring: which occasionally happened anyway (e.g. your comments around players moving towards the corner position)
I'm tracking that issue here: https://github.com/GallagherAiden/footballSimulationEngine/issues/20
If you can add your iteration json for when it occurs it should help me get a better understanding of the issue. Feel free to raise other issues not relating to players getting stuck in another ticket :)

**Comment by GallagherAiden** [comment]
I think some of the problems we were seeing before are now being resolved here: https://github.com/GallagherAiden/footballSimulationEngine/commit/1bbeb6b74a3ba77e5365182fee468c729c88a9af
