### ISSUE TITLE
Difference Between Player's startPos, originPos & relativePos

### ISSUE THREAD

**Issue by amjadhashim** [GallagherAiden/footballSimulationEngine#32]
hi all,

this is not at all an issue but rather me looking for help.

what is actually the difference between startPos, originPos & relativePos?
if I were to update a player's position on the pitch by each single iteration on timer tick, which value should I use?

thanks in advance for your help!

**Comment by GallagherAiden** [comment]
Hello @amjadhashim 

Short answer: 
**StartPos** = first position at start of game and current position throughout iterations
**OriginPos** = retention of base formations so that team keeps shape
**RelativePos** = where the players want to be on the pitch for movement decisions. 

long answer:
startPos = refers to the players position on the field. At the start of the game, both teams should be placed as if they are on the top of a vertical pitch. e.g no greater than the width of the pitch and no greater than the pitch height. The simulator than puts players into their correct position depending on whether they are on the top or the bottom of the pitch (home or away). The startPOS is then used to determine a players current position on the pitch at any given time - goal kicks, free kicks, offside etc. 

originPos = Is used to get players back into their base position on the pitch so that they retain their formation throughout the game. I separate startPOS from originPOS to allow tactical changes outside of the base formation e.g. to allow wingers to become more attacking you could increase the y position during the game (if say, a manager was to change the style of play mid game)

relativePos = this is what I use to infer where players want to be moving towards e.g. if a team is attacking, the relative position reflects that. 


let me know if you would like some more detail

**Comment by GallagherAiden** [comment]
There's an issue raised already to make the variables match their purpose:
https://github.com/GallagherAiden/footballSimulationEngine/issues/25

**Comment by GallagherAiden** [comment]
Hi @amjadhashim - closing this issue and will update the naming of the positions in 
https://github.com/GallagherAiden/footballSimulationEngine/issues/25 let me know if there's anything else you want help with and comment on the issue above if you want to influence the decision making for the naming changes

**Comment by amjadhashim** [comment]
Hi @GallagherAiden thank you for your reply. sorry for my late reply. wasn't working for the last few days. from your answers, I can understand that for visualization purpose I should use values from startPos to update my view. thanks for the great engine! looking forward to your next updates on the engine.
